logging:
  level:
    ROOT: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.web.client.DefaultRestClient: OFF
    com.wan.ekyc: DEBUG

spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    name: ekyc
    url: jdbc:h2:mem:ekyc;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

application:
  innovative:
    url: <innovative-api-url>
    username: <innovative-api-username>
    password: <innovative-api-password>
    api-key: <innovative-api-key>
    okid-api-key: <innovative-okid-api-key>
    okdoc-api-key: <innovative-okdoc-api-key>
    okface-api-key: <innovative-okface-api-key>
    oklive-api-key: <innovative-oklive-api-key>